name: shahid_suleimani_library
description: کتابخانه شهید حاج قاسم سلیمانی
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.1

  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Animation
  flutter_animate: ^4.5.0
  animations: ^2.0.11  # برای Material Motion

  # Avatar
  flutter_dice_bear: ^1.0.1
  flutter_svg: ^2.0.9

  # PDF Viewer
  pdf_viewer_pro: ^0.0.1

  # Audio Player
  just_audio: ^0.10.5
  audio_session: ^0.2.0
  just_audio_background: ^0.0.1-beta.11

  # Video Player
  awesome_video_player: ^1.0.5

  # Offline Sync
  flutter_offline_sync_manager: ^0.1.2
  connectivity_plus: ^6.0.0

  # Firebase
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

  # Rating
  awesome_rating: ^0.0.4

  # Profile
  flutter_profile_kit: ^1.0.0
  image_picker: ^1.0.7

  # Networking
  http: ^1.2.0

  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700